# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
#


[font]
normal = { family = "BlexMono Nerd Font Mono" }

[window]
opacity = 0.888

[colors]
[colors.primary]
background = "#232220"
foreground = "#a9a49f"

[colors.normal]
black   = "#232220"
red     = "#cb704f"
green   = "#8a8d4c"
yellow  = "#bfaa48"
blue    = "#d1b187"
magenta = "#b08c52"
cyan    = "#61928b"
white   = "#a9a49f"

[colors.bright]
black   = "#5c5a57"
red     = "#c87252"
green   = "#909048"
yellow  = "#d8c85a"
blue    = "#e0c99e"
magenta = "#c9a464"
cyan    = "#608e8a"
white   = "#8aacaa"

[colors.cursor]
text   = "#232220"
cursor = "#cac5be"

#   ______   __       ______
#  /_____/\ /_/\     /_____/\
#  \:::_ \ \\:\ \    \:::_ \ \
#   \:\ \ \ \\:\ \    \:\ \ \ \
#    \:\ \ \ \\:\ \____\:\ \ \ \
#     \:\_\ \ \\:\/___/\\:\/.:| |
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/
#
