# foot.ini
# By OldJobobo (https://github.com/OldJobobo)

[main]
font=BlexMono Nerd Font Mono:size=10

[colors-dark]
alpha=0.888
background=232220
foreground=a9a49f
cursor=232220 d1b187
selection-foreground=232220
selection-background=d1b187

# Normal (0-7)
regular0=232220
regular1=cb704f
regular2=8a8d4c
regular3=bfaa48
regular4=d1b187
regular5=b08c52
regular6=61928b
regular7=a9a49f

# Bright (8-15)
bright0=5c5a57
bright1=c87252
bright2=909048
bright3=d8c85a
bright4=e0c99e
bright5=c9a464
bright6=608e8a
bright7=8aacaa

#   ______   __       ______
#  /_____/\ /_/\     /_____/\
#  \:::_ \ \\:\ \    \:::_ \ \
#   \:\ \ \ \\:\ \    \:\ \ \ \
#    \:\ \ \ \\:\ \____\:\ \ \ \
#     \:\_\ \ \\:\/___/\\:\/.:| |
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/
#
