-- Generated by scripts/hypr2lua.
-- Source: omarchy-the-navigator-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(b08c52ff)", "rgba(b08c52ff)", "rgba(b08c52ff)", "rgba(8aacaaff)", "rgba(b08c52ff)", "rgba(b08c52ff)", "rgba(b08c52ff)" },
  angle = 130,
}
local inactiveBorderColor = "rgb(4a5860)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 3,
    gaps_in = 10,
    gaps_out = 20,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    active_opacity = 1.05,
    inactive_opacity = 0.93,
    blur = {
      enabled = true,
      size = 2,
      passes = 1,
      contrast = 0.888,
      brightness = 0.42,
      vibrancy = 0.30,
      noise = 0.02,
      vibrancy_darkness = 0.20,
      input_methods = false,
      popups = true,
      popups_ignorealpha = 0.65,
    },
    shadow = {
      enabled = true,
      range = 18,
      render_power = 3,
      color = "rgba(141312dd)",
      color_inactive = "rgba(14131299)",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 2,
  bezier = "default",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 2,
  bezier = "default",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 2,
  bezier = "default",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 2,
  bezier = "default",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 2,
  bezier = "default",
})
